CREATE DATABASE LaptopWorld
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

use LaptopWorld;


CREATE TABLE user (
    IdUser INT AUTO_INCREMENT PRIMARY KEY,
    HoTen VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    MatKhau VARCHAR(255) NOT NULL,
    SoDienThoai VARCHAR(20),
    VaiTro ENUM('user', 'admin') DEFAULT 'user',
    TrangThai TINYINT(1) DEFAULT 1,
    ThoiDiemTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    CapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;



CREATE TABLE DanhMuc (
    IdDanhMuc INT AUTO_INCREMENT PRIMARY KEY,
    TenDanhMuc VARCHAR(255) NOT NULL UNIQUE,
    MoTaDanhMuc TEXT
) ENGINE=InnoDB;


CREATE TABLE ThuongHieu (
    IdThuongHieu INT AUTO_INCREMENT PRIMARY KEY,
    TenThuongHieu VARCHAR(255) NOT NULL,
    MoTaThuongHieu TEXT
) ENGINE=InnoDB;


CREATE TABLE SanPham (
    IdSanPham INT AUTO_INCREMENT PRIMARY KEY,
    TenSanPham VARCHAR(255) NOT NULL,
    MoTaSanPham TEXT,
    GiaSanPham DECIMAL(12,2) NOT NULL DEFAULT 0,
    SoLuongSanPham INT NOT NULL DEFAULT 0,
    ThuongHieuId INT,
    DanhMucId INT,
    TrangThaiSanPham ENUM('DangBan', 'NgungBan', 'An') DEFAULT 'DangBan',
    FOREIGN KEY (ThuongHieuId) REFERENCES ThuongHieu(IdThuongHieu) ON DELETE SET NULL,
    FOREIGN KEY (DanhMucId) REFERENCES DanhMuc(IdDanhMuc) ON DELETE SET NULL
) ENGINE=InnoDB;


CREATE TABLE HinhAnhSanPham (
    IdHinhAnhSanPham INT AUTO_INCREMENT PRIMARY KEY,
    SanPhamId INT NOT NULL,
    Url VARCHAR(1024) NOT NULL,
    AnhMacDinh TINYINT(1) DEFAULT 0,
    FOREIGN KEY (SanPhamId) REFERENCES SanPham(IdSanPham) ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE GioHang (
    IdGioHang INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT NOT NULL,
    UNIQUE KEY GioHangNguoiDung(UserId),
    FOREIGN KEY (UserId) REFERENCES user(IdUser) ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE ChiTietGioHang (
    IdChiTietGioHang INT AUTO_INCREMENT PRIMARY KEY,
    GioHangId INT NOT NULL,
    SanPhamId INT NOT NULL,
    SoLuongChiTietGioHang INT NOT NULL DEFAULT 1,
    FOREIGN KEY (GioHangId) REFERENCES GioHang(IdGioHang) ON DELETE CASCADE,
    FOREIGN KEY (SanPhamId) REFERENCES SanPham(IdSanPham) ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE DonHang (
    IdDonHang INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT NOT NULL,
    MaDonHang VARCHAR(255) NOT NULL UNIQUE,
    TrangThaiDonHang ENUM('Cho xu ly', 'Xac nhan', 'Dang giao', 'Da giao', 'Da huy', 'HoanTien')
        DEFAULT 'Cho xu ly',
    DiaChiGiao TEXT,
    TongTien DECIMAL(12,2) NOT NULL DEFAULT 0,
    DonHangTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES user(IdUser)
) ENGINE=InnoDB;


CREATE TABLE ChiTietDonHang (
    IdChiTietDonHang INT AUTO_INCREMENT PRIMARY KEY,
    DonHangId INT NOT NULL,
    SanPhamId INT NOT NULL,
    SoLuong INT NOT NULL,
    GiaBan DECIMAL(12,2) NOT NULL,
    ChiTietDonHangTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (DonHangId) REFERENCES DonHang(IdDonHang) ON DELETE CASCADE,
    FOREIGN KEY (SanPhamId) REFERENCES SanPham(IdSanPham) ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE HoaDon (
    IdHoaDon INT AUTO_INCREMENT PRIMARY KEY,
    DonHangId INT NOT NULL,
    MaHoaDon VARCHAR(255) NOT NULL,
    SoTien DECIMAL(12,2) NOT NULL,
    NgayXuat DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (DonHangId) REFERENCES DonHang(IdDonHang) ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE ThanhToan (
    IdThanhToan INT AUTO_INCREMENT PRIMARY KEY,
    DonHangId INT NOT NULL,
    PhuongThucThanhToan ENUM('Tien mat', 'Chuyen Khoan', 'Quet the') NOT NULL,
    TrangThaiThanhToan ENUM('Cho xac nhan', 'Thanh cong', 'That Bai') DEFAULT 'Cho xac nhan',
    MaGiaoDich VARCHAR(255),
    SoTien DECIMAL(12,2) NOT NULL,
    NgayThanhToan DATETIME,
    FOREIGN KEY (DonHangId) REFERENCES DonHang(IdDonHang) ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE DanhGia (
    IdDanhGia INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT,
    SanPhamId INT,
    ParentId INT DEFAULT NULL,
    XepLoai INT CHECK (XepLoai BETWEEN 1 AND 5),
    BinhLuan TEXT,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    CapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES user(IdUser) ON DELETE CASCADE,
    FOREIGN KEY (SanPhamId) REFERENCES SanPham(IdSanPham) ON DELETE CASCADE,
    FOREIGN KEY (ParentId) REFERENCES DanhGia(IdDanhGia) ON DELETE CASCADE
) ENGINE=InnoDB;



CREATE TABLE IF NOT EXISTS TinTuc (
    IdTinTuc INT PRIMARY KEY AUTO_INCREMENT,
    TieuDe VARCHAR(255) NOT NULL,
    NoiDung TEXT NOT NULL,
    AnhBia VARCHAR(255),
    UserId INT NOT NULL,
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LuotXem INT DEFAULT 0,
    TrangThai ENUM('HienThi', 'An') DEFAULT 'HienThi',
    FOREIGN KEY (UserId) REFERENCES user(IdUser) ON DELETE CASCADE,
    INDEX idx_trangthai (TrangThai),
    INDEX idx_ngaytao (NgayTao)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS BinhLuanTinTuc (
    IdBinhLuan INT PRIMARY KEY AUTO_INCREMENT,
    TinTucId INT NOT NULL,
    UserId INT NOT NULL,
    NoiDung TEXT NOT NULL,
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (TinTucId) REFERENCES TinTuc(IdTinTuc) ON DELETE CASCADE,
    FOREIGN KEY (UserId) REFERENCES user(IdUser) ON DELETE CASCADE,
    INDEX idx_tintuc (TinTucId),
    INDEX idx_ngaytao (NgayTao)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE DanhGia 
ADD COLUMN ParentId INT DEFAULT NULL AFTER SanPhamId,
ADD FOREIGN KEY (ParentId) REFERENCES DanhGia(IdDanhGia) ON DELETE CASCADE;

ALTER TABLE DanhGia 
ADD COLUMN CapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE DanhGia 
MODIFY COLUMN XepLoai INT NULL;



CREATE TABLE LienHe (
    IdLienHe INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT,
    TieuDe VARCHAR(255),
    NoiDung TEXT,
    TrangThai ENUM('Moi', 'Da Doc', 'Da tra loi') DEFAULT 'Moi',
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES user(IdUser) ON DELETE CASCADE
) ENGINE=InnoDB;


-- INSERT INTO user (HoTen, Email, MatKhau, SoDienThoai, VaiTro)
INSERT INTO user (HoTen, Email, MatKhau, SoDienThoai, VaiTro) VALUES('Admin', 'admin@gmail.com', '123', '0394127625', 'admin');


select * from user;
select * from SanPham;



