-- Tạo bảng TinTuc
CREATE TABLE IF NOT EXISTS TinTuc (
    IdTinTuc INT PRIMARY KEY AUTO_INCREMENT,
    TieuDe VARCHAR(255) NOT NULL,
    NoiDung TEXT NOT NULL,
    AnhBia VARCHAR(255),
    UserId INT NOT NULL,
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LuotXem INT DEFAULT 0,
    TrangThai ENUM('HienThi', 'An') DEFAULT 'HienThi',
    FOREIGN KEY (UserId) REFERENCES user(IdUser) ON DELETE CASCADE,
    INDEX idx_trangthai (TrangThai),
    INDEX idx_ngaytao (NgayTao)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tạo bảng BinhLuanTinTuc
CREATE TABLE IF NOT EXISTS BinhLuanTinTuc (
    IdBinhLuan INT PRIMARY KEY AUTO_INCREMENT,
    TinTucId INT NOT NULL,
    UserId INT NOT NULL,
    NoiDung TEXT NOT NULL,
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (TinTucId) REFERENCES TinTuc(IdTinTuc) ON DELETE CASCADE,
    FOREIGN KEY (UserId) REFERENCES user(IdUser) ON DELETE CASCADE,
    INDEX idx_tintuc (TinTucId),
    INDEX idx_ngaytao (NgayTao)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
