-- Add technical specifications columns to SanPham table
USE LaptopWorld;

ALTER TABLE SanPham
ADD COLUMN KieuOCung VARCHAR(100) COMMENT 'SSD, HDD, SSD + HDD',
ADD COLUMN DungLuongOCung VARCHAR(50) COMMENT '256GB, 512GB, 1TB',
ADD COLUMN CongNgheManHinh VARCHAR(100) COMMENT 'IPS, OLED, TN',
ADD COLUMN TanSoQuet VARCHAR(50) COMMENT '60Hz, 120Hz, 144Hz',
ADD COLUMN DoPhanGiai VARCHAR(50) COMMENT 'FHD, 2K, 4K',
ADD COLUMN Pin VARCHAR(50) COMMENT '50Wh, 70Wh, 90Wh',
ADD COLUMN XuatXu VARCHAR(100) COMMENT 'Trung Quốc, Việt Nam, USA',
ADD COLUMN TrongLuong VARCHAR(50) COMMENT '1.5kg, 2.0kg';

-- Verify
DESCRIBE SanPham;
